### ISSUE TITLE
ESP crashes if using dynamicaly created objects

### ISSUE THREAD

**Issue by vortigont** [rwmingis/InterruptButton#4] opened 2022-02-06 22:06 UTC
Using dynamically created button objects leads to a crash on ISR

```
int pin = 4;
InterruptButton *btn1 = nullptr;

setup(){
      btn1 = new InterruptButton(pin, INPUT_PULLUP, LOW);
      btn1.syncKeyPress[0] =  [](){ Serial.println("Button 1 press");};

}

```
It makes impossible to use run-time assigned pins for buttons.

**Comment by rwmingis** [comment] 2022-02-06 23:31
Thanks @vortigont for your continued testing.  Could it be due to
dynamic allocation of memory relating to code placed into internal RAM, ie
the use of IRAM_ATTR?  I have not found the need to do it with dynamic
memory allocation, but don't want to limit the library if someone does.

Also, am considering making more of the member functions as static class
functions and just have member functions pass their object's reference to
the corresponding static class functions where possible so they are only
defined once in the memory rather than replicated with each instance.
Maybe it will save a bit of memory space.

I will get some time this week to do a bit of work on it, I think for now,
I will put it on a known issues list and start tackling some of the more
pressing ones (excuse the pun) like longkepress event ones timeout expires

Cheers
Rob

**Comment by vortigont** [comment] 2022-02-07 10:25
Thanks for your feedback, @rwmingis ! Appreciate your attention )
The need for dynamic allocation for me is pretty simple - I do not know at compile time which pin I'm going to attach button to. It's value will be defined at run time via WebUI setup.
Pls, take your time, no hurry, do not wanna be an elephant in your china shop :) I will do further investigation meanwhile.
May come up with a different approach to consider. In general I was thinking about throwing out Arduino's methods if possible and end up with solely IDF approach, but wrapped with C++ classes for sure. Not that I'm Arduino hater, but ESP32 has pretty good SDK now and for the lib it's better to be as much compatible as possible and not limited to Arduino's framework.
Also might worth trying to replace ISR functional callback with a RTOS message or event queue. PIN ISR only generates event and actual processing is done via separate thread. This way we may get rid of loop() dependency at all and make a totally async lib were all callback could be triggered without making long time critical ISR's and not dependent to timing skew due to blocking loop() calls. But that's a long story, just throwing my ideas here

**Comment by rwmingis** [comment] 2022-07-09 05:28
HI @vortigont, has been some time.  I've done a bit of tidy up, in an attempt to fix your issues with deleting dynamically allocated buttons.  It's not pretty, and may not be guaranteed to work, but I haven't been able to reproduce your crash issue (I did experience crashes accidently using the [] operator with delete, but none since removing).

Only trying to close this out so I can move onto other things. I think this library is working good enough for me.  Happy to implment a simple fix, just not looking for a drastic change at this time to the structure.  Thanks for all you input so far! 

Cheers.

**Closed by rwmingis** 2022-07-09 05:28 UTC
